---
version: '3.7'

services:
  portfolio:
    build:
      context: ./html/
      dockerfile: Dockerfile
    image: portfolio
    hostname: portfolio
    container_name: portfolio
    ports:
      - "8080:80"
