---
version: '3.7'

services:
  portfolio:
    build:
      context: ./portfolio/
      dockerfile: dockerfile
      args:
      - PORT=${PORT}
    image: portfolio
    hostname: portfolio
    container_name: portfolio
    command: yarn start
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "${PORT}:${PORT}"
